---
name: Yaml Lint
on: [push]  # yamllint disable-line rule:truthy
jobs:
  YamlLinter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: config.yaml
          config_file: .github/workflows/yaml-linter-config.yml
